### ISSUE TITLE
Pull Requestに対して自動でlinterを実行する

### ISSUE THREAD

**Issue by polyester-CTRL** [Siv3D/OpenSiv3D#836]
**追加する機能の内容 | Describe the solution you'd like**
- GitHub Actionsを使って、OpenSiv3D本体のリポジトリにPull Requestを出した際に自動でlinterを実行したいです。
- 具体例としては、 [インデントがtabに統一されていないコード](https://github.com/Siv3D/OpenSiv3D/pull/828#discussion_r901084588)などがあったときに、レビュアーが指摘する前にエラーや警告を出します。

**その機能の追加によって解決する問題 | Is your feature request related to a problem? Please describe.**
- レビュアーの負担を軽減することが期待できます。

**備考 | Additional context**

**Comment by Reputeless** [comment]
ご提案ありがとうございます。検討します。
具体的な追加コードは用意できますか？
実装会での作業とするのも良いです。

**Comment by polyester-CTRL** [comment]
追加コードについてはこれから用意します。
もし日程的に実装会に参加できるようなら、そこで作業しようと思います。

**Comment by Reputeless** [comment]
ありがとうございます。心強いです。

**Comment by Reputeless** [comment]
2022年6月21日(火) 14:15 polyester ***@***.***>:

**Comment by polyester-CTRL** [comment]
コーディング規約を細かく設定できる点から、clang-formatを使用する予定です。
もし別のツールが良いなどの意見がありましたら、コメントをお願いします。

**Comment by Reputeless** [comment]
メジャーなツールなので大丈夫だと思います。
設定するのはタブスペース、{ } 位置ぐらいでいいのかなとは思っています。

**Comment by polyester-CTRL** [comment]
clang-formatを試しに使ってみたところ、一部のルールだけチェックするようなことはできないようです。
例えば、ポインタや参照の位置( ``int* a;`` もしくは  `` int *a;`` )の違い、``#include <foo>``が``# include <foo>``となっていることなどもすべて警告として表示されることが分かりました。
できるだけ既存のコードで警告を出さないようにしたいのですが、警告を出さないようにオプションを調整するところで手間取っています。

**Comment by Reputeless** [comment]
v0.8 世代で 0 からフルスクラッチで Siv3D を書き直すので、そのときに導入するのも手かもしれないなと思いました。

**Comment by polyester-CTRL** [comment]
0から書き直すタイミングなら問題なく導入できそうですね。
導入する際は、.clang-formatでコーディング規約を設定していただけるとスムーズにlinterを設定できると思います。よろしくお願いします。

**Comment by polyester-CTRL** [comment]
参考までに、現在設定している.clang-formatオプションです。完全に同じではありませんが、今のSiv3Dのソースコードに近い記法にフォーマットできます。
```
Language: Cpp
BasedOnStyle: LLVM
Standard: c++20
UseTab: ForIndentation
NamespaceIndentation: All
TabWidth: 1
IndentWidth: 1
PointerAlignment: Left
BreakBeforeBraces: Allman
AllowShortIfStatementsOnASingleLine: false
IndentCaseLabels: false
ColumnLimit: 0
AccessModifierOffset: -1
FixNamespaceComments: false
BraceWrapping:
  AfterFunction: true
  BeforeElse: true
  AfterNamespace: true
  AfterStruct: true
```
